In [1]:
from dask.distributed import Client
import dask.array as da
import numpy as np
client = Client()
print("Dashboard link:", client.dashboard_link)

distributed.diskutils - INFO - Found stale lock file and directory '/Users/cbla0002/Documents/code/phd/dask/dask-worker-space/worker-e2uu84wb', purging
distributed.diskutils - INFO - Found stale lock file and directory '/Users/cbla0002/Documents/code/phd/dask/dask-worker-space/worker-gkn9e7qn', purging
distributed.diskutils - INFO - Found stale lock file and directory '/Users/cbla0002/Documents/code/phd/dask/dask-worker-space/worker-2oe2hvbw', purging
distributed.diskutils - INFO - Found stale lock file and directory '/Users/cbla0002/Documents/code/phd/dask/dask-worker-space/worker-285ebz7l', purging
distributed.diskutils - INFO - Found stale lock file and directory '/Users/cbla0002/Documents/code/phd/dask/dask-worker-space/worker-t581aub6', purging
distributed.diskutils - INFO - Found stale lock file and directory '/Users/cbla0002/Documents/code/phd/dask/dask-worker-space/worker-8xx722c5', purging
distributed.diskutils - INFO - Found stale lock file and directory '/Users/cbla0002/Docu

Dashboard link: http://127.0.0.1:8787/status


In [2]:
def complex_computation(x):
    # Perform some complex operations
    y = da.sin(x) ** 2
    z = da.cos(x) ** 2
    return da.sqrt(y + z)

def main():
    # Create a large random Dask array
    x = da.random.random(size=(20000, 20000), chunks=(1000, 1000))

    # Perform a complex computation
    result = complex_computation(x)

    # Compute the result
    computed_result = result.compute()
    print(computed_result)

main()

[[1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 ...
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]
 [1. 1. 1. ... 1. 1. 1.]]


In [1]:
client.close()

NameError: name 'client' is not defined