In [1]:
import numpy as np
import xarray as xr

In [18]:
# There are no NaN in  TaiESm1
# ds = xr.open_dataset('/g/data/oi10/replicas/CMIP6/CMIP/AS-RCEC/TaiESM1/historical/r1i1p1f1/Amon/ta/gn/v20200623/ta_Amon_TaiESM1_historical_r1i1p1f1_gn_185001-201412.nc')
# da = ds['ta'].isel(time = 0)
# if np.isnan(da).any():
#     print("There are NaN values in the DataArray.")
# else:
#     print("There are no NaN values in the DataArray.")

In [14]:
# There are some NaN in IPSL
dataset = 'IPSL'
ds = xr.open_dataset('/g/data/oi10/replicas/CMIP6/CMIP/IPSL/IPSL-CM6A-LR/historical/r1i1p1f1/Amon/ta/gr/v20180803/ta_Amon_IPSL-CM6A-LR_historical_r1i1p1f1_gr_185001-201412.nc')
da = ds['ta'].isel(time = slice(1, 5))
if np.isnan(da).any():
    print("There are NaN values in the DataArray.")
else:
    print("There are no NaN values in the DataArray.")

There are NaN values in the DataArray.


In [3]:
da.plev

<xarray.DataArray 'plev' (plev: 19)>
array([100000.,  92500.,  85000.,  70000.,  60000.,  50000.,  40000.,  30000.,
        25000.,  20000.,  15000.,  10000.,   7000.,   5000.,   3000.,   2000.,
         1000.,    500.,    100.], dtype=float32)
Coordinates:
  * plev     (plev) float32 1e+05 9.25e+04 8.5e+04 7e+04 ... 1e+03 500.0 100.0
Attributes:
    name:           plev
    standard_name:  air_pressure
    long_name:      pressure
    units:          Pa
    positive:       down

In [ ]:
# da = ds['ta'].isel(time = 1200)
# da.sel(plev = 850e2).plot()

In [13]:
theta =  da * (1000e2 / da.plev)**(287/1005)                  # theta = T (P_0/P)^(R_d/C_p)
plevs1, plevs2 = [400e2, 250e2], [925e2, 700e2]
da1, da2 = [theta.sel(plev=slice(plevs1[0], plevs1[1])), theta.sel(plev=slice(plevs2[0], plevs2[1]))] if not dataset == 'ERA5' else [theta.sel(plev=slice(plevs1[1], plevs1[0])), theta.sel(plev=slice(plevs2[1], plevs2[0]))] 
da = ((da1 * da1.plev).sum(dim='plev') / da1.plev.sum(dim='plev')) - ((da2 * da2.plev).sum(dim='plev') / da2.plev.sum(dim='plev'))   
da

<xarray.DataArray (time: 4, lat: 143, lon: 144)>
array([[[232.06894 , 232.06894 , 232.06894 , ..., 232.06894 ,
         232.06894 , 232.06894 ],
        [230.82465 , 230.90445 , 231.00113 , ..., 230.54153 ,
         230.64969 , 230.71167 ],
        [229.86554 , 230.08008 , 230.28093 , ..., 229.05295 ,
         229.31393 , 229.62256 ],
        ...,
        [ 35.553772,  35.504333,  35.462616, ...,  35.659546,
          35.62982 ,  35.58661 ],
        [ 35.76291 ,  35.754517,  35.73633 , ...,  35.80475 ,
          35.783264,  35.775635],
        [ 35.724304,  35.724304,  35.724304, ...,  35.724304,
          35.724304,  35.724304]],

       [[233.4047  , 233.4047  , 233.4047  , ..., 233.4047  ,
         233.4047  , 233.4047  ],
        [232.57234 , 232.4768  , 232.42538 , ..., 232.50052 ,
         232.50272 , 232.5729  ],
        [232.08133 , 232.15805 , 232.263   , ..., 231.50702 ,
         231.79568 , 231.96194 ],
...
        [ 36.51303 ,  36.47943 ,  36.45108 , ...,  36.59958 ,
          36.574036,  36.542297],
        [ 36.209747,  36.197845,  36.1846  , ...,  36.25699 ,
          36.24005 ,  36.225098],
        [ 35.740356,  35.740356,  35.740356, ...,  35.740356,
          35.740356,  35.740356]],

       [[227.88919 , 227.88919 , 227.88919 , ..., 227.88919 ,
         227.88919 , 227.88919 ],
        [225.81447 , 226.02838 , 226.20688 , ..., 225.30956 ,
         225.44412 , 225.70282 ],
        [224.55576 , 224.94495 , 225.2402  , ..., 223.48837 ,
         223.99812 , 224.11743 ],
        ...,
        [ 34.221954,  34.187225,  34.16452 , ...,  34.29062 ,
          34.271637,  34.25949 ],
        [ 34.177216,  34.158722,  34.15689 , ...,  34.248657,
          34.234985,  34.211548],
        [ 34.016174,  34.016174,  34.016174, ...,  34.016174,
          34.016174,  34.016174]]], dtype=float32)
Coordinates:
  * lat      (lat) float32 -90.0 -88.73 -87.46 -86.2 ... 86.2 87.46 88.73 90.0
  * lon      (lon) float32 0.0 2.5 5.0 7.5 10.0 ... 350.0 352.5 355.0 357.5
  * time     (time) datetime64[ns] 1850-02-15 ... 1850-05-16T12:00:00

In [15]:
theta =  da * (1000e2 / da.plev)**(287/1005)                  # theta = T (P_0/P)^(R_d/C_p)
plevs_high, plevs_low = [400e2, 250e2], [925e2, 700e2]        # pressure levels in ERA are reversed to cmip
da_high, da_low = [theta.sel(plev=slice(plevs_high[0], plevs_high[1])), theta.sel(plev=slice(plevs_low[0], plevs_low[1]))] if not dataset == 'ERA5' else [theta.sel(plev=slice(plevs_high[1], plevs_high[0])), theta.sel(plev=slice(plevs_low[1], plevs_low[0]))] 
da = ((da_high * da_high.plev).sum(dim='plev') / da_high.plev.sum(dim='plev')) - ((da_low * da_low.plev).sum(dim='plev') / da_low.plev.sum(dim='plev'))   
da

<xarray.DataArray (time: 4, lat: 143, lon: 144)>
array([[[232.06894 , 232.06894 , 232.06894 , ..., 232.06894 ,
         232.06894 , 232.06894 ],
        [230.82465 , 230.90445 , 231.00113 , ..., 230.54153 ,
         230.64969 , 230.71167 ],
        [229.86554 , 230.08008 , 230.28093 , ..., 229.05295 ,
         229.31393 , 229.62256 ],
        ...,
        [ 35.553772,  35.504333,  35.462616, ...,  35.659546,
          35.62982 ,  35.58661 ],
        [ 35.76291 ,  35.754517,  35.73633 , ...,  35.80475 ,
          35.783264,  35.775635],
        [ 35.724304,  35.724304,  35.724304, ...,  35.724304,
          35.724304,  35.724304]],

       [[233.4047  , 233.4047  , 233.4047  , ..., 233.4047  ,
         233.4047  , 233.4047  ],
        [232.57234 , 232.4768  , 232.42538 , ..., 232.50052 ,
         232.50272 , 232.5729  ],
        [232.08133 , 232.15805 , 232.263   , ..., 231.50702 ,
         231.79568 , 231.96194 ],
...
        [ 36.51303 ,  36.47943 ,  36.45108 , ...,  36.59958 ,
          36.574036,  36.542297],
        [ 36.209747,  36.197845,  36.1846  , ...,  36.25699 ,
          36.24005 ,  36.225098],
        [ 35.740356,  35.740356,  35.740356, ...,  35.740356,
          35.740356,  35.740356]],

       [[227.88919 , 227.88919 , 227.88919 , ..., 227.88919 ,
         227.88919 , 227.88919 ],
        [225.81447 , 226.02838 , 226.20688 , ..., 225.30956 ,
         225.44412 , 225.70282 ],
        [224.55576 , 224.94495 , 225.2402  , ..., 223.48837 ,
         223.99812 , 224.11743 ],
        ...,
        [ 34.221954,  34.187225,  34.16452 , ...,  34.29062 ,
          34.271637,  34.25949 ],
        [ 34.177216,  34.158722,  34.15689 , ...,  34.248657,
          34.234985,  34.211548],
        [ 34.016174,  34.016174,  34.016174, ...,  34.016174,
          34.016174,  34.016174]]], dtype=float32)
Coordinates:
  * lat      (lat) float32 -90.0 -88.73 -87.46 -86.2 ... 86.2 87.46 88.73 90.0
  * lon      (lon) float32 0.0 2.5 5.0 7.5 10.0 ... 350.0 352.5 355.0 357.5
  * time     (time) datetime64[ns] 1850-02-15 ... 1850-05-16T12:00:00